language: node_js
node_js: 6
script:
- npm test
deploy:
- provider: npm
  email: wmhilton@gmail.com
  api_key: "$NPM_PUBLISH_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: wmhilton/webtorrentify-github-release
- provider: releases
  api_key: "$PUTASSET_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: wmhilton/webtorrentify-github-release
